apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: roar
data:
  mysql.database: registry
  mysql.user: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: roar-db 
  namespace: roar
spec:
  selector:
    matchLabels:
      app: roar-db
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
        app: roar-db
    spec:
      containers:
      - name: mysql
        image: quay.io/techupskills2/roar-db:v4
        ports:
        - name: mysql
          containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.database
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mysqlsecret
                key: mysqlpassword
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: mysqlrootpassword
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.user
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: roar
spec:
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
  selector:
    name: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: roar
type: Opaque
data:
  mysqlpassword: YWRtaW4=
  mysqlrootpassword: cm9vdCsx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roar-web
  labels:
    name: roar-web
    app: roar-web
  namespace: roar
spec:
  selector:
    matchLabels:
      app: roar-web  
  replicas: 1
  template:
    metadata:
      labels:
        name: roar-web
        app: roar-web
    spec:
      containers:
      - name: roar-web
        image: quay.io/techupskills/roar-web:v1
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: roar-web
  labels:
    name: roar-web
  namespace: roar
spec:
  type: NodePort
  ports:
  - port: 8089
    targetPort: 8080
    nodePort: 31790
  selector:
    name: roar-web
---
